title: web Barreto
email: robson.rbarreto@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rrbarreto.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  rrbarreto

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
search_enabled: true
plugins:
  - jekyll-feed

aux_links:
    "Find me on LinkedIn":
      - "https://www.linkedin.com/in/robsonrbarreto"

